# Generated by Django 4.2.5 on 2023-09-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logname', models.CharField(max_length=250)),
                ('logimg', models.ImageField(upload_to='photo')),
                ('logdesc', models.TextField()),
            ],
        ),
    ]
